In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('Logs/log_sus.csv', sep=';', header=None, names=[ "Start-time","Empty", "Description"])
df.drop(columns=['Empty'], inplace=True)
df.head()

            Start-time                      Description
0  2023-01-18 16:35:14                              NaN
1  2023-01-18 16:35:21                  go to line 100
2  2023-01-18 16:35:26                  toggle comment
3  2023-01-18 16:35:30                    find kconfig
4  2023-01-18 16:35:35  move between searches 6 times

In [5]:
df['Start-time'] = pd.to_datetime(df['Start-time'])
df['End-time'] = df['Start-time'].shift(-1)

In [6]:
df.head()

           Start-time                      Description            End-time
0 2023-01-18 16:35:14                              NaN 2023-01-18 16:35:21
1 2023-01-18 16:35:21                  go to line 100  2023-01-18 16:35:26
2 2023-01-18 16:35:26                  toggle comment  2023-01-18 16:35:30
3 2023-01-18 16:35:30                    find kconfig  2023-01-18 16:35:35
4 2023-01-18 16:35:35  move between searches 6 times   2023-01-18 16:35:45

In [7]:
df['Duration(sec)'] = (df['End-time'] - df['Start-time']).dt.total_seconds()
df['Elapsed(sec)'] = (df['Start-time'] - df['Start-time'].min()).dt.total_seconds()
df.head()

,Start-time,Description,End-time,Duration(sec),Elapsed(sec)
0,2023-01-18 16:35:14,NaN,2023-01-18 16:35:21,7.0,0.0
1,2023-01-18 16:35:21,go to line 100,2023-01-18 16:35:26,5.0,7.0
2,2023-01-18 16:35:26,toggle comment,2023-01-18 16:35:30,4.0,12.0
3,2023-01-18 16:35:30,find kconfig,2023-01-18 16:35:35,5.0,16.0
4,2023-01-18 16:35:35,move between searches 6 times,2023-01-18 16:35:45,10.0,21.0

In [8]:
df.to_csv('Logs/log_sus_duration.csv', sep=';', header=None, index=False, float_format='%.2f')

In [9]:
df.head(46)

,Start-time,Description,End-time,Duration(sec),Elapsed(sec)
0,2023-01-18 16:35:14,NaN,2023-01-18 16:35:21,7.0,0.0
1,2023-01-18 16:35:21,go to line 100,2023-01-18 16:35:26,5.0,7.0
2,2023-01-18 16:35:26,toggle comment,2023-01-18 16:35:30,4.0,12.0
3,2023-01-18 16:35:30,find kconfig,2023-01-18 16:35:35,5.0,16.0
4,2023-01-18 16:35:35,move between searches 6 times,2023-01-18 16:35:45,10.0,21.0
5,2023-01-18 16:35:45,close find bar,2023-01-18 16:35:45,0.0,31.0
6,2023-01-18 16:35:45,standby 30 sec,2023-01-18 16:36:15,30.0,31.0
7,2023-01-18 16:36:15,go to line 200,2023-01-18 16:36:20,5.0,61.0
8,2023-01-18 16:36:20,select 10 lines,2023-01-18 16:36:23,3.0,66.0
9,2023-01-18 16:36:23,delete selected text,2023-01-18 16:36:33,10.0,69.0
10,2023-01-18 16:36:33,go 5 lines down,2023-01-18 16:36:35,2.0,79.0
11,2023-01-18 16:36:35,delete line,2023-01-18 16:36:45,10.0,81.0
12,2023-01-18 16:36:45,undo,2023-01-18 16:36:47,2.0,91.0
13,2023-01-18 16:36:47,undo again,2023-01-18 16:36:49,2.0,93.0
14,2023-01-18 16:36:49,redo,2023-01-18 16:36:54,5.0,95.0
15,2023-01-18 16:36:54,increase font size,2023-01-18 16:37:00,6.0,100.0
16,2023-01-18 16:37:00,toggle folding,2023-01-18 16:37:08,8.0,106.0
17,2023-01-18 16:37:08,decrease font size,2023-01-18 16:37:14,6.0,114.0
18,2023-01-18 16:37:14,enter full screen mode,2023-01-18 16:37:19,5.0,120.0
19,2023-01-18 16:37:19,exit full screen mode,2023-01-18 16:37:24,5.0,125.0
20,2023-01-18 16:37:24,print preview,2023-01-18 16:37:30,6.0,130.0
21,2023-01-18 16:37:30,go 2 lines down,2023-01-18 16:37:32,2.0,136.0
22,2023-01-18 16:37:32,set bookmark,2023-01-18 16:37:35,3.0,138.0
23,2023-01-18 16:37:35,go 5 lines down,2023-01-18 16:37:41,6.0,141.0
24,2023-01-18 16:37:41,select 10 lines,2023-01-18 16:37:47,6.0,147.0
25,2023-01-18 16:37:47,cut,2023-01-18 16:37:52,5.0,153.0
26,2023-01-18 16:37:52,standby 30 sec,2023-01-18 16:38:22,30.0,158.0
27,2023-01-18 16:38:22,go 5 lines down,2023-01-18 16:38:25,3.0,188.0
28,2023-01-18 16:38:25,paste,2023-01-18 16:38:30,5.0,191.0
29,2023-01-18 16:38:30,close,2023-01-18 16:38:33,3.0,196.0
30,2023-01-18 16:38:33,discard the current file,2023-01-18 16:38:44,11.0,199.0
31,2023-01-18 16:38:44,open new file,2023-01-18 16:38:49,5.0,210.0
32,2023-01-18 16:38:49,standby 5 sec,2023-01-18 16:38:54,5.0,215.0
33,2023-01-18 16:38:54,type lorem ipsum,2023-01-18 16:39:24,30.0,220.0
34,2023-01-18 16:39:24,enable spell checking,2023-01-18 16:39:29,5.0,250.0
35,2023-01-18 16:39:29,toggle line numbers,2023-01-18 16:39:34,5.0,255.0
36,2023-01-18 16:39:34,go to the begining of the line,2023-01-18 16:39:39,5.0,260.0
37,2023-01-18 16:39:39,disable spell checking,2023-01-18 16:39:44,5.0,265.0
38,2023-01-18 16:39:44,uppercase,2023-01-18 16:39:47,3.0,270.0
39,2023-01-18 16:39:47,toggle line numbers,2023-01-18 16:39:52,5.0,273.0
40,2023-01-18 16:39:52,lowercase,2023-01-18 16:39:57,5.0,278.0
41,2023-01-18 16:39:57,save file,2023-01-18 16:40:06,9.0,283.0
42,2023-01-18 16:40:06,create new file,2023-01-18 16:40:11,5.0,292.0
43,2023-01-18 16:40:11,type lorem ipsum,2023-01-18 16:40:36,25.0,297.0
44,2023-01-18 16:40:36,quit kate,2023-01-18 16:40:45,9.0,322.0
45,2023-01-18 16:40:45,NaN,2023-01-18 16:40:48,3.0,331.0