In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('log_sus.csv', sep=';', header=None, names=["Iterations", "Start-time","Empty", "Description"])
df.drop(columns=['Empty'], inplace=True)
df.head()

    Iterations           Start-time                      Description
0  iteration 1  2023-02-01 08:53:20                     startTestrun
1  iteration 1  2023-02-01 08:53:27                  go to line 100
2  iteration 1  2023-02-01 08:53:32                  toggle comment
3  iteration 1  2023-02-01 08:53:36                    find kconfig
4  iteration 1  2023-02-01 08:53:41  move between searches 6 times

In [4]:
df['Start-time'] = pd.to_datetime(df['Start-time'])
df['End-time'] = df['Start-time'].shift(-1)

In [5]:
df.head()

,Iterations,Start-time,Description,End-time
0,iteration 1,2023-02-01 08:53:20,startTestrun,2023-02-01 08:53:27
1,iteration 1,2023-02-01 08:53:27,go to line 100,2023-02-01 08:53:32
2,iteration 1,2023-02-01 08:53:32,toggle comment,2023-02-01 08:53:36
3,iteration 1,2023-02-01 08:53:36,find kconfig,2023-02-01 08:53:41
4,iteration 1,2023-02-01 08:53:41,move between searches 6 times,2023-02-01 08:53:51

In [24]:
df['Duration(sec)'] = (df['End-time'] - df['Start-time']).dt.total_seconds()
df['Elapsed(sec)'] = (df['Start-time'] - df['Start-time'].min()).dt.total_seconds()
df.head()

,Iterations,Start-time,Description,End-time,Duration(sec),Elapsed(sec)
0,iteration 1,2023-02-01 08:53:20,startTestrun,2023-02-01 08:53:27,7.0,0.0
1,iteration 1,2023-02-01 08:53:27,go to line 100,2023-02-01 08:53:32,5.0,7.0
2,iteration 1,2023-02-01 08:53:32,toggle comment,2023-02-01 08:53:36,4.0,12.0
3,iteration 1,2023-02-01 08:53:36,find kconfig,2023-02-01 08:53:41,5.0,16.0
4,iteration 1,2023-02-01 08:53:41,move between searches 6 times,2023-02-01 08:53:51,10.0,21.0

In [30]:
df.to_csv('log_sus_duration.csv', sep=';', header=None, index=False, float_format='%.2f')

In [26]:
df.head(46)

,Iterations,Start-time,Description,End-time,Duration(sec),Elapsed(sec)
0,iteration 1,2023-02-01 08:53:20,startTestrun,2023-02-01 08:53:27,7.0,0.0
1,iteration 1,2023-02-01 08:53:27,go to line 100,2023-02-01 08:53:32,5.0,7.0
2,iteration 1,2023-02-01 08:53:32,toggle comment,2023-02-01 08:53:36,4.0,12.0
3,iteration 1,2023-02-01 08:53:36,find kconfig,2023-02-01 08:53:41,5.0,16.0
4,iteration 1,2023-02-01 08:53:41,move between searches 6 times,2023-02-01 08:53:51,10.0,21.0
5,iteration 1,2023-02-01 08:53:51,close find bar,2023-02-01 08:53:51,0.0,31.0
6,iteration 1,2023-02-01 08:53:51,standby 30 sec,2023-02-01 08:54:21,30.0,31.0
7,iteration 1,2023-02-01 08:54:21,go to line 200,2023-02-01 08:54:26,5.0,61.0
8,iteration 1,2023-02-01 08:54:26,select 10 lines,2023-02-01 08:54:29,3.0,66.0
9,iteration 1,2023-02-01 08:54:29,delete selected text,2023-02-01 08:54:39,10.0,69.0
10,iteration 1,2023-02-01 08:54:39,go 5 lines down,2023-02-01 08:54:41,2.0,79.0
11,iteration 1,2023-02-01 08:54:41,delete line,2023-02-01 08:54:51,10.0,81.0
12,iteration 1,2023-02-01 08:54:51,undo,2023-02-01 08:54:53,2.0,91.0
13,iteration 1,2023-02-01 08:54:53,undo again,2023-02-01 08:54:55,2.0,93.0
14,iteration 1,2023-02-01 08:54:55,redo,2023-02-01 08:55:00,5.0,95.0
15,iteration 1,2023-02-01 08:55:00,increase font size,2023-02-01 08:55:06,6.0,100.0
16,iteration 1,2023-02-01 08:55:06,toggle folding,2023-02-01 08:55:14,8.0,106.0
17,iteration 1,2023-02-01 08:55:14,decrease font size,2023-02-01 08:55:20,6.0,114.0
18,iteration 1,2023-02-01 08:55:20,enter full screen mode,2023-02-01 08:55:25,5.0,120.0
19,iteration 1,2023-02-01 08:55:25,exit full screen mode,2023-02-01 08:55:30,5.0,125.0
20,iteration 1,2023-02-01 08:55:30,print preview,2023-02-01 08:55:36,6.0,130.0
21,iteration 1,2023-02-01 08:55:36,go 2 lines down,2023-02-01 08:55:38,2.0,136.0
22,iteration 1,2023-02-01 08:55:38,set bookmark,2023-02-01 08:55:41,3.0,138.0
23,iteration 1,2023-02-01 08:55:41,go 5 lines down,2023-02-01 08:55:47,6.0,141.0
24,iteration 1,2023-02-01 08:55:47,select 10 lines,2023-02-01 08:55:53,6.0,147.0
25,iteration 1,2023-02-01 08:55:53,cut,2023-02-01 08:55:58,5.0,153.0
26,iteration 1,2023-02-01 08:55:58,standby 30 sec,2023-02-01 08:56:28,30.0,158.0
27,iteration 1,2023-02-01 08:56:28,go 5 lines down,2023-02-01 08:56:31,3.0,188.0
28,iteration 1,2023-02-01 08:56:31,paste,2023-02-01 08:56:36,5.0,191.0
29,iteration 1,2023-02-01 08:56:36,close,2023-02-01 08:56:39,3.0,196.0
30,iteration 1,2023-02-01 08:56:39,discard the current file,2023-02-01 08:56:50,11.0,199.0
31,iteration 1,2023-02-01 08:56:50,open new file,2023-02-01 08:56:55,5.0,210.0
32,iteration 1,2023-02-01 08:56:55,standby 5 sec,2023-02-01 08:57:00,5.0,215.0
33,iteration 1,2023-02-01 08:57:00,type lorem ipsum,2023-02-01 08:57:30,30.0,220.0
34,iteration 1,2023-02-01 08:57:30,enable spell checking,2023-02-01 08:57:35,5.0,250.0
35,iteration 1,2023-02-01 08:57:35,toggle line numbers,2023-02-01 08:57:40,5.0,255.0
36,iteration 1,2023-02-01 08:57:40,go to the begining of the line,2023-02-01 08:57:45,5.0,260.0
37,iteration 1,2023-02-01 08:57:45,disable spell checking,2023-02-01 08:57:50,5.0,265.0
38,iteration 1,2023-02-01 08:57:50,uppercase,2023-02-01 08:57:53,3.0,270.0
39,iteration 1,2023-02-01 08:57:53,toggle line numbers,2023-02-01 08:57:58,5.0,273.0
40,iteration 1,2023-02-01 08:57:58,lowercase,2023-02-01 08:58:03,5.0,278.0
41,iteration 1,2023-02-01 08:58:03,save file,2023-02-01 08:58:12,9.0,283.0
42,iteration 1,2023-02-01 08:58:12,create new file,2023-02-01 08:58:17,5.0,292.0
43,iteration 1,2023-02-01 08:58:17,type lorem ipsum,2023-02-01 08:58:42,25.0,297.0
44,iteration 1,2023-02-01 08:58:42,quit kate,2023-02-01 08:58:51,9.0,322.0
45,iteration 1,2023-02-01 08:58:51,NaN,2023-02-01 08:58:54,3.0,331.0